application: aeistmobile-backoffice
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url:  /static
  static_dir: static

- url: /Resources/img
  static_dir: Resources/img

- url: /test.*
  script: gaeunit.application

- url: /api.*
  script: aeistmobile-api.app

- url: /.*
  script: aeistmobile-backoffice.app
  login: admin

libraries:
- name: jinja2
  version: 2.6
